import React from "react";

const DataProtection: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 py-12 pt-24 text-justify text-gray-800">
      <h1 className="text-3xl font-bold mb-6">Data Protection</h1>

      <p className="mb-4">
        This website uses Google Analytics, a web analysis service provided by
        Google Inc. (&quot;Google&quot;). Google Analytics uses so called &quot;cookies&quot;, text
        files placed on your computer, to help the website analyze how users use
        the site. The information generated by the cookie about your use of the
        website is generally transferred to a Google server in the USA and saved
        there. However, if IP anonymization is activated on this website, Google
        will shorten your IP address within member states of the European Union
        or other contracting states to the Agreement on the European Economic
        Area beforehand. Only in exceptional cases will the full IP address be
        transmitted to a Google server in the USA and shortened there. On behalf
        of the operator of this website, Google will use this information to
        evaluate your use of the website, to compile reports on website activity
        and to provide the website operator with other services relating to
        website activity and internet usage. The IP address transmitted by your
        browser as part of Google Analytics will not be merged with other Google
        data. You can prevent cookies from being saved by setting your browser
        software accordingly; However, we would like to point out that in this
        case you may not be able to use all functions of this website to their
        full extent. You can also prevent Google from collecting the data
        generated by the cookie and relating to your use of the website
        (including your IP address) and from processing this data by downloading
        and installing the browser plug-in available under the following link:{" "}
        <a
          href="http://tools.google.com/dlpage/gaoptout"
          target="_blank"
          rel="noopener noreferrer"
          className="underline"
        >
          http://tools.google.com/dlpage/gaoptout
        </a>
      </p>

      <p className="mb-4">
        Further information on terms of use and data protection can be found in
        the Google Analytics terms and conditions or in the Google Analytics
        overview. We would like to point out that Google Analytics has been
        extended on this website to include the code &quot;gat._anonymizeIp()&quot;
        in order to ensure anonymous collection of IP addresses (so-called IP
        masking).
      </p>
    </div>
  );
};

export default DataProtection;